---
title: "Time series with regression variables"
author: "Javier Cara"
date: "Nov 2018"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_float: true
    theme: flatly
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
load("data_temp.RData")
ndata = nrow(data_temp)
```

```{r}
plot(data_temp$temp, type = "l", xlim = c(900,ndata))
lines(data_temp$temp_1, col = "blue")
lines(data_temp$temp_2, col = "green")
lines(data_temp$temp_3, col = "red")
```

# MLE using EM algorithm

## Data

- Split the data for model estimation and prediction

```{r}
day1 = ndata - 23 # 2018-11-05-0:00:00
day2 = ndata # 2018-11-05-23:00:00
y = data_temp$temp[1:day1]
u = rbind(c(0,y[1:(day1-1)]), data_temp$temp_1[1:day1])
ya = data_temp$temp[day1:day2]
ua = rbind(data_temp$temp[(day1-1):(day2-1)], data_temp$temp_1[day1:day2])
```


## Starting values: subspace algorithm

```{r}
nx = 3
ny = 1
nu = nrow(u)
ssm_sub = emssm::ACQRS_sub(y,nx,ny)
Ai = ssm_sub$A
Ci = ssm_sub$C
Qi = ssm_sub$Q
Ri = ssm_sub$R
m1i = rep(0,nx)
P1i = diag(nx)
Bi = array(0, c(nx,nu))
Di = array(0, c(ny,nu))
```

## EM algorithm

```{r}
ssm_e = emssm::ABCDQR_em(y,u,Ai,Bi,Ci,Di,Qi,Ri,m1i,P1i,max_iter = 50,ny = ny,nx = nx, nu = nu,txo = T)
```

```{r}
plot(ssm_e$loglikv, type = "l")
```


# Estimated time series

- The estimates of the parameters are:

```{r}
Ae = ssm_e$A
Be = ssm_e$B
Ce = ssm_e$C
De = ssm_e$D
Qe = ssm_e$Q
Re = ssm_e$R
m1e = ssm_e$m1
P1e = ssm_e$P1
```

```{r}
kf <- emssm::ABCDQR_kfilter(y,u,Ae,Be,Ce,De,Qe,Re,m1e,P1e,nx,ny,nu)
ye <- Ce %*% kf$xtt1[,-length(y)] + De %*% u
```

```{r}
plot(y, type = "l")
lines(1:length(y),ye, col = "blue", lwd = 1)
```

# Checking the residuals

```{r}
res <- y - ye
```

```{r}
plot(res[1,], type = 'l')
```

```{r}
acf(res[1,])
```

# Predicting new values

## Predictions using real data

```{r}
num_pred = day2 - day1 + 1
yp = matrix(0, nrow = ny, ncol = num_pred)
ypi1 = matrix(0, nrow = ny, ncol = num_pred)
ypi2 = matrix(0, nrow = ny, ncol = num_pred)
for (t in 1:num_pred){
  y_upd = c(y,ya[t-1]) # updated data
  u_upd = cbind(u,ua[,t-1]) # updated data
  pred = emssm::ABCDQR_predict(y_upd,u_upd,Ae,Be,Ce,De,Qe,Re,m1e,P1e,nx,ny,nu,ua[,t],n_ahead=1)
  yp[,t] = pred$yp
  ypi1[,t] = pred$ypi1
  ypi2[,t] = pred$ypi2
}
```

```{r}
plot(data_temp$temp, type = "l", xlim = c(980, nrow(data_temp)))

tt = day1:day2
lines(tt,yp[1,], col = "blue")
lines(tt,ypi1[1,], col = "blue", lty = 3)
lines(tt,ypi2[1,], col = "blue", lty = 3)
```

## Predictions using predicted values

```{r}
num_pred = day2 - day1 + 1
yp = matrix(0, nrow = ny, ncol = num_pred)
ypi1 = matrix(0, nrow = ny, ncol = num_pred)
ypi2 = matrix(0, nrow = ny, ncol = num_pred)
for (t in 1:num_pred){
  y_upd = c(y,ya[t-1]) # updated data
  u_upd = cbind(u,yp[,t-1]) # updated data
  if (t == 1){
    u_new = rbind(y[length(y)], data_temp$temp_1[day1+t])
  } else{
    u_new = rbind(yp[t-1], data_temp$temp_1[day1+t])
  }
  
  pred = emssm::ABCDQR_predict(y_upd,u_upd,Ae,Be,Ce,De,Qe,Re,m1e,P1e,nx,ny,nu,u_new,n_ahead=1)
  yp[,t] = pred$yp
  ypi1[,t] = pred$ypi1
  ypi2[,t] = pred$ypi2
}
```

```{r}
plot(data_temp$temp, type = "l", xlim = c(980, nrow(data_temp)))

tt = day1:day2
lines(tt,yp[1,], col = "blue")
lines(tt,ypi1[1,], col = "blue", lty = 3)
lines(tt,ypi2[1,], col = "blue", lty = 3)
```


