---
title: "Introduction to estimation and prediction of state space models"
author: "Javier Cara"
date: "2020-02"
output: 
  html_document:
    toc: false
    theme: flatly
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br>

# Contents

1. [Introduction](01_intro.html).

2. Univariate time series:
    a. [Simulation](02_univariate_simula.html)
    b. [Applying the Kalman filter and smoother](02_univariate_kalman.html)
    c. [Maximum likelihood estimation using Newton-Raphson algorithm](02_univariate_mle_newton.html)
    d. [Maximum likelihood estimation using the EM algorithm](02_univariate_mle_em.html)
    
3. Multivariate time series:
    a. [Maximum likelihood estimation using Newton-Raphson algorithm](03_multivariate_mle_newton.html)
    b. [Maximum likelihood estimation using the EM algorithm](03_multivariate_mle_em.html)
    
4. Multivariate time series with exogenous inputs:
    a. [Maximum likelihood estimation using Newton-Raphson algorithm](04_multivariateX_mle_newton.html)
    b. [Maximum likelihood estimation using the EM algorithm](04_multivariateX_mle_em.html)
    
    
